---
- name: Install Apache web server
  become: yes
  apt:
    name: lighttpd
    state: latest
    update_cache: yes

- name: Update Apache configuration
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^server.port                 = 80'
    line: 'server.port = 9090'

- name: Start Apache service
  become: yes
  service:
    name: lighttpd
    state: started
